enable-magisk-update = false
parallel-jobs = 1

rv-brand = "RV"

[YouTube]
version = "19.16.39"
patcher-args = "-e 'Change header' -Oheader='premium*header'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
arch = "arm64-v8a"

[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"
